### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lhafkamp** [Sidstumple/minor-wafs#1]
Making those sectionList/sectionsId variables looks clean!

![screen shot 2017-02-09 at 19 18 11](https://cloud.githubusercontent.com/assets/14187210/22796917/9822cede-eefc-11e6-9db8-98478158bfb3.png)

Since you're only using 1 if & else you could use the ternary operator to make your code shorter like this:

sectionsId === route ? sectionList.classList.remove('hide') : sectionList.classList.add('hide');

Which does the same thing but with less code! Amazing.

**Comment by dandevri** [comment]
In addition to @lhafkamp;

Not sure if you even need to use: `var sectionsId = "#" + sections[i].id;` You're sections already have the same ID as the Hash value you are trying to target.

**Comment by Razpudding** [comment]
Good points guys
